spring.application.name=SaludarDatos
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mariadb://172.17.0.2:3306/saludos
spring.datasource.username=root
spring.datasource.password=123
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect